import type { SampleForm } from './types'

export const COMPLIANCE_PROGRAM_ASSESSMENT: SampleForm = {
    label: 'Compliance Program Assessment',
    submittedAt: '2025-12-31T14:30:00.000Z',
    definition: {
        id: '0f6b8e5d-cc6b-4d4d-809e-b996967d828b',
        version: '1.0.0',
        title: 'Compliance Program Effectiveness Review',
        description: "Assess the effectiveness of your organization's crypto compliance program",
        content: [
            {
                id: 1,
                type: 'select',
                label: 'Overall compliance program rating',
                options: [
                    { value: 1, label: '1 – Critical Deficiencies' },
                    { value: 2, label: '2 – Significant Gaps' },
                    { value: 3, label: '3 – Adequate' },
                    { value: 4, label: '4 – Strong' },
                    { value: 5, label: '5 – Best-in-Class' },
                ],
                validation: { required: true },
            },
            {
                id: 2,
                type: 'string',
                label: 'Key compliance program strengths',
                condition: { field: 1, op: 'gte', value: 4 },
            },
            {
                id: 3,
                type: 'string',
                label: 'Critical deficiencies requiring immediate remediation',
                condition: { field: 1, op: 'lte', value: 2 },
                validation: { required: true, minLength: 20 },
            },
            {
                id: 4,
                type: 'select',
                label: 'AML/KYC program maturity',
                options: [
                    { value: 1, label: '1 – Critical Deficiencies' },
                    { value: 2, label: '2 – Significant Gaps' },
                    { value: 3, label: '3 – Adequate' },
                    { value: 4, label: '4 – Strong' },
                    { value: 5, label: '5 – Best-in-Class' },
                ],
                validation: { required: true },
            },
            {
                id: 5,
                type: 'select',
                label: 'Transaction monitoring effectiveness',
                options: [
                    { value: 1, label: '1 – Critical Deficiencies' },
                    { value: 2, label: '2 – Significant Gaps' },
                    { value: 3, label: '3 – Adequate' },
                    { value: 4, label: '4 – Strong' },
                    { value: 5, label: '5 – Best-in-Class' },
                ],
                validation: { required: true },
            },
            {
                id: 6,
                type: 'string',
                label: 'Describe transaction monitoring gaps',
                condition: { field: 5, op: 'lte', value: 2 },
                validation: { required: true, minLength: 20 },
            },
            {
                id: 7,
                type: 'select',
                label: 'Sanctions screening coverage',
                options: [
                    { value: 1, label: '1 – Critical Deficiencies' },
                    { value: 2, label: '2 – Significant Gaps' },
                    { value: 3, label: '3 – Adequate' },
                    { value: 4, label: '4 – Strong' },
                    { value: 5, label: '5 – Best-in-Class' },
                ],
                validation: { required: true },
            },
            {
                id: 8,
                type: 'boolean',
                label: 'Travel Rule fully implemented?',
            },
            {
                id: 9,
                type: 'select',
                label: 'Staff compliance training adequacy',
                options: [
                    { value: 1, label: '1 – Critical Deficiencies' },
                    { value: 2, label: '2 – Significant Gaps' },
                    { value: 3, label: '3 – Adequate' },
                    { value: 4, label: '4 – Strong' },
                    { value: 5, label: '5 – Best-in-Class' },
                ],
                validation: { required: true },
            },
            {
                id: 10,
                type: 'number',
                label: 'Compliance training hours per employee (annual)',
                condition: { field: 9, op: 'gte', value: 3 },
                validation: { min: 0 },
            },
            {
                id: 11,
                type: 'array',
                label: 'Priority improvement areas',
                item: { type: 'string', label: 'Area' },
                validation: { maxItems: 10 },
            },
            {
                id: 12,
                type: 'date',
                label: 'Assessment date',
                validation: { required: true },
            },
            {
                id: 13,
                type: 'string',
                label: 'Assessor name',
                validation: { required: true },
            },
            {
                id: 14,
                type: 'string',
                label: 'Additional observations',
                validation: { maxLength: 5000 },
            },
        ],
    },
    values: {
        '1': 4,
        '2': 'Robust real-time transaction monitoring with low false-positive rate; strong sanctions screening integration across all supported chains.',
        '4': 4,
        '5': 4,
        '7': 5,
        '8': true,
        '9': 4,
        '10': 24,
        '11': ['Cross-chain analytics', 'DeFi protocol monitoring', 'NFT transaction coverage'],
        '12': '2025-12-01T00:00:00.000Z',
        '13': 'Sarah Lim, Chief Compliance Officer',
    },
}
