import type { SampleForm } from './types'

export const COMPLIANCE_DISCLOSURE: SampleForm = {
    label: 'Compliance Disclosure',
    definition: {
        id: 'fbee2b4d-1d83-478a-85e2-b25c0a4133a2',
        version: '1.0.0',
        title: 'Compliance Disclosure Assessment',
        description: 'Comprehensive product and entity disclosure questionnaire',
        content: [
            {
                id: 1,
                type: 'section',
                title: 'Initial Screening',
                description: 'Preliminary product classification',
                content: [
                    {
                        id: 2,
                        type: 'boolean',
                        label: 'Does your organization offer a financial product?',
                        validation: { required: true },
                    },
                    {
                        id: 3,
                        type: 'boolean',
                        label: 'Is the product represented as a digital token on a blockchain?',
                        condition: { field: 2, op: 'eq', value: true },
                        validation: { required: true },
                    },
                    {
                        id: 4,
                        type: 'boolean',
                        label: 'Is the token backed by underlying reserve holdings?',
                        condition: { field: 3, op: 'eq', value: true },
                        validation: { required: true },
                    },
                ],
            },
            {
                id: 5,
                type: 'section',
                title: 'Entity Profile',
                description: 'Details about the issuing organization and its product',
                content: [
                    {
                        id: 6,
                        type: 'string',
                        label: 'Product designation',
                        validation: { required: true },
                    },
                    {
                        id: 7,
                        type: 'string',
                        label: 'Brief product summary',
                        validation: { required: true, minLength: 10, maxLength: 2000 },
                    },
                    {
                        id: 8,
                        type: 'string',
                        label: 'Registered legal entity name',
                        validation: { required: true },
                    },
                    {
                        id: 9,
                        type: 'select',
                        label: 'Corporate structure type',
                        options: [
                            { value: 'trust', label: 'Trust' },
                            { value: 'lp', label: 'Limited Partnership' },
                            { value: 'spc', label: 'Special Purpose Company' },
                            { value: 'corporation', label: 'Corporation' },
                            { value: 'dao', label: 'Decentralized Organization' },
                            { value: 'other', label: 'Other' },
                        ],
                        validation: { required: true },
                    },
                    {
                        id: 10,
                        type: 'string',
                        label: 'Registration jurisdiction',
                        validation: { required: true },
                    },
                    {
                        id: 11,
                        type: 'string',
                        label: 'Organization overview',
                        validation: { required: true, minLength: 10, maxLength: 5000 },
                    },
                    {
                        id: 12,
                        type: 'string',
                        label: 'Corporate website URL',
                    },
                    {
                        id: 13,
                        type: 'string',
                        label: 'Social media handle',
                    },
                    {
                        id: 14,
                        type: 'string',
                        label: 'Professional network profile URL',
                    },
                ],
            },
            {
                id: 15,
                type: 'section',
                title: 'On-Chain Product Specifications',
                description: 'Token-specific information',
                condition: { field: 3, op: 'eq', value: true },
                content: [
                    {
                        id: 16,
                        type: 'string',
                        label: 'Contract address on deployment network',
                        validation: { required: true },
                    },
                    {
                        id: 17,
                        type: 'string',
                        label: 'Token display name',
                        validation: { required: true },
                    },
                    {
                        id: 18,
                        type: 'string',
                        label: 'Abbreviated ticker symbol',
                        validation: { required: true },
                    },
                    {
                        id: 19,
                        type: 'select',
                        label: 'Image licensing rights',
                        options: [
                            { value: 'public-domain', label: 'Public Domain / CC0' },
                            { value: 'cc-by', label: 'CC By (Attribution)' },
                            { value: 'cc-by-nc', label: 'CC BY-NC (Non-Commercial)' },
                            { value: 'all-rights', label: 'All Rights Reserved' },
                            { value: 'nft-license', label: 'NFT License' },
                        ],
                        validation: { required: true },
                    },
                    {
                        id: 20,
                        type: 'string',
                        label: 'Technical documentation URL',
                        validation: { required: true },
                    },
                    {
                        id: 21,
                        type: 'string',
                        label: 'Official project website',
                        validation: { required: true },
                    },
                    {
                        id: 22,
                        type: 'string',
                        label: 'Deployment network',
                        validation: { required: true },
                    },
                    {
                        id: 23,
                        type: 'string',
                        label: 'Protocol standard',
                        validation: { required: true },
                    },
                    {
                        id: 24,
                        type: 'select',
                        label: 'Wallet verification method',
                        options: [
                            { value: 'owner', label: 'Verified by Owner' },
                            { value: 'co-issuer', label: 'Verified by Co-Issuer' },
                        ],
                        validation: { required: true },
                    },
                ],
            },
            {
                id: 25,
                type: 'section',
                title: 'Off-Chain Product Specifications',
                description: 'Non-digital product information',
                condition: {
                    and: [
                        { field: 2, op: 'eq', value: true },
                        { field: 3, op: 'ne', value: true },
                    ],
                },
                content: [
                    {
                        id: 26,
                        type: 'string',
                        label: 'Reference identifier (CUSIP, ISIN, or internal)',
                        validation: { required: true },
                    },
                    {
                        id: 27,
                        type: 'date',
                        label: 'Origination date',
                        validation: { required: true },
                    },
                    {
                        id: 28,
                        type: 'string',
                        label: 'Custodial or transfer agent',
                    },
                ],
            },
            {
                id: 29,
                type: 'section',
                title: 'Regulatory Classification',
                description: 'Product classification and regulatory categorization',
                content: [
                    {
                        id: 30,
                        type: 'boolean',
                        label: 'Does this represent ownership of, or exposure to, a regulated financial instrument?',
                        validation: { required: true },
                    },
                    {
                        id: 31,
                        type: 'select',
                        label: 'Which legal structure best describes this product?',
                        options: [
                            { value: 'fund', label: 'Investment Vehicle (Fund / ETF)' },
                            { value: 'note', label: 'Structured Instrument (Note)' },
                            { value: 'receivables', label: 'Credit Pool (Receivables)' },
                            { value: 'resource', label: 'Resource Rights Vehicle (Mineral / Royalty)' },
                            { value: 'spc', label: 'Protected Lending Structure (SPC)' },
                            { value: 'unknown', label: 'Unclassified' },
                        ],
                        condition: { field: 30, op: 'eq', value: true },
                        validation: { required: true },
                    },
                    {
                        id: 32,
                        type: 'select',
                        label: 'Governing jurisdiction of the issuing vehicle',
                        options: [
                            { value: 'us', label: 'United States' },
                            { value: 'sg', label: 'Singapore' },
                            { value: 'ky', label: 'Cayman Islands' },
                            { value: 'vg', label: 'British Virgin Islands' },
                            { value: 'bs', label: 'Bahamas' },
                            { value: 'au', label: 'Australia' },
                            { value: 'other', label: 'Other' },
                        ],
                        validation: { required: true },
                    },
                    {
                        id: 33,
                        type: 'boolean',
                        label: 'Are there restrictions on who may hold this product?',
                        validation: { required: true },
                    },
                    {
                        id: 34,
                        type: 'string',
                        label: 'Describe holder restriction type and eligibility requirements',
                        condition: { field: 33, op: 'eq', value: true },
                        validation: { required: true, minLength: 10 },
                    },
                    {
                        id: 35,
                        type: 'string',
                        label: 'Attestation that no transfer restrictions apply, with stated basis',
                        condition: { field: 33, op: 'eq', value: false },
                        validation: { required: true },
                    },
                ],
            },
            {
                id: 36,
                type: 'section',
                title: 'Structural Safeguards',
                description: 'Structural risk assessment and protective measures',
                content: [
                    {
                        id: 37,
                        type: 'section',
                        title: 'Insolvency Protection',
                        content: [
                            {
                                id: 38,
                                type: 'boolean',
                                label: 'Is the product held or issued through a bankruptcy-remote or segregated structure?',
                                validation: { required: true },
                            },
                            {
                                id: 39,
                                type: 'string',
                                label: 'Describe the organizational structure',
                                condition: { field: 38, op: 'eq', value: true },
                                validation: { required: true },
                            },
                            {
                                id: 40,
                                type: 'string',
                                label: 'Explain the security interest or segregation mechanism',
                                condition: { field: 38, op: 'eq', value: true },
                                validation: { required: true },
                            },
                            {
                                id: 41,
                                type: 'string',
                                label: 'Explain creditor priority arrangement',
                                condition: { field: 38, op: 'eq', value: false },
                                validation: { required: true },
                            },
                            {
                                id: 42,
                                type: 'string',
                                label: 'Disclose any commingling risk',
                                condition: { field: 38, op: 'eq', value: false },
                                validation: { required: true },
                            },
                            {
                                id: 43,
                                type: 'string',
                                label: 'Describe mitigation controls in place',
                                condition: { field: 38, op: 'eq', value: false },
                                validation: { required: true },
                            },
                        ],
                    },
                    {
                        id: 44,
                        type: 'section',
                        title: 'Asset Safekeeping',
                        content: [
                            {
                                id: 45,
                                type: 'boolean',
                                label: 'Are the underlying assets held in independent third-party custody?',
                                validation: { required: true },
                            },
                            {
                                id: 46,
                                type: 'string',
                                label: 'Custodian identity',
                                condition: { field: 45, op: 'eq', value: true },
                                validation: { required: true },
                            },
                            {
                                id: 47,
                                type: 'string',
                                label: 'Confirm account segregation arrangements',
                                condition: { field: 45, op: 'eq', value: true },
                                validation: { required: true },
                            },
                            {
                                id: 48,
                                type: 'boolean',
                                label: 'Are any reserve assets held in offline or cold storage?',
                                condition: { field: 45, op: 'eq', value: true },
                            },
                            {
                                id: 49,
                                type: 'string',
                                label: 'Describe the proof-of-control protocol',
                                condition: {
                                    and: [
                                        { field: 45, op: 'eq', value: true },
                                        { field: 48, op: 'eq', value: true },
                                    ],
                                },
                                validation: { required: true },
                            },
                            {
                                id: 50,
                                type: 'string',
                                label: 'Describe internal custody controls',
                                condition: { field: 45, op: 'eq', value: false },
                                validation: { required: true },
                            },
                            {
                                id: 51,
                                type: 'string',
                                label: 'Disclose counterparty risk',
                                condition: { field: 45, op: 'eq', value: false },
                                validation: { required: true },
                            },
                            {
                                id: 52,
                                type: 'string',
                                label: 'Describe incident response procedures',
                                condition: { field: 45, op: 'eq', value: false },
                                validation: { required: true },
                            },
                        ],
                    },
                    {
                        id: 53,
                        type: 'section',
                        title: 'Valuation Assurance',
                        content: [
                            {
                                id: 54,
                                type: 'select',
                                label: 'What independent assurance exists for product valuation?',
                                options: [
                                    { value: 'audited', label: 'Audited financial statements' },
                                    { value: 'third-party', label: 'Third-party valuation agent' },
                                    { value: 'internal', label: 'Internal valuation only' },
                                    { value: 'none', label: 'None' },
                                ],
                                validation: { required: true },
                            },
                            {
                                id: 55,
                                type: 'string',
                                label: 'Enhanced risk disclosure and justification for valuation approach',
                                condition: {
                                    or: [
                                        { field: 54, op: 'eq', value: 'internal' },
                                        { field: 54, op: 'eq', value: 'none' },
                                    ],
                                },
                                validation: { required: true },
                            },
                            {
                                id: 56,
                                type: 'string',
                                label: 'Who performs your independent attestation?',
                                validation: { required: true },
                            },
                            {
                                id: 57,
                                type: 'date',
                                label: 'Date of last independent attestation',
                                validation: { required: true },
                            },
                        ],
                    },
                ],
            },
            {
                id: 58,
                type: 'section',
                title: 'Reserve Portfolio',
                description: 'Reserve asset details and composition',
                condition: { field: 4, op: 'eq', value: true },
                content: [
                    {
                        id: 59,
                        type: 'select',
                        label: 'Primary backing asset category',
                        options: [
                            { value: 'cash', label: 'Cash deposit (bank)' },
                            { value: 'tbill', label: 'Government security' },
                            { value: 'repo', label: 'Overnight reverse repo' },
                            { value: 'mmf', label: 'Money market fund' },
                            { value: 'corp-bond', label: 'Corporate bond' },
                            { value: 'digital-asset', label: 'Tokenized asset / stablecoin' },
                            { value: 'crypto', label: 'Crypto asset' },
                            { value: 'commodity', label: 'Physical commodity' },
                            { value: 'real-estate', label: 'Real estate' },
                            { value: 'other', label: 'Other' },
                        ],
                        validation: { required: true },
                    },
                    {
                        id: 60,
                        type: 'string',
                        label: 'Token contract address of the backing crypto asset',
                        condition: { field: 59, op: 'eq', value: 'crypto' },
                        validation: { required: true },
                    },
                    {
                        id: 61,
                        type: 'boolean',
                        label: 'Does this backing asset itself hold reserves?',
                        condition: { field: 59, op: 'eq', value: 'crypto' },
                    },
                    {
                        id: 62,
                        type: 'string',
                        label: 'Provide verification source for the reserve composition',
                        condition: { field: 61, op: 'eq', value: true },
                        validation: { required: true },
                    },
                    {
                        id: 63,
                        type: 'string',
                        label: 'Vault or custody account holding this reserve asset',
                        condition: { field: 61, op: 'eq', value: true },
                        validation: { required: true },
                    },
                    {
                        id: 64,
                        type: 'string',
                        label: 'Bank account reference or routing number',
                        condition: { field: 59, op: 'eq', value: 'cash' },
                        validation: { required: true },
                    },
                    {
                        id: 65,
                        type: 'boolean',
                        label: 'Is this a term deposit or certificate of deposit?',
                        condition: { field: 59, op: 'eq', value: 'cash' },
                    },
                    {
                        id: 66,
                        type: 'date',
                        label: 'Maturity date of the deposit',
                        condition: { field: 65, op: 'eq', value: true },
                        validation: { required: true },
                    },
                    {
                        id: 67,
                        type: 'boolean',
                        label: 'Does the amount exceed insured deposit limits?',
                        condition: { field: 59, op: 'eq', value: 'cash' },
                    },
                    {
                        id: 68,
                        type: 'string',
                        label: 'Security identifier (CUSIP or ISIN)',
                        condition: { field: 59, op: 'in', value: ['tbill', 'corp-bond', 'mmf'] },
                        validation: { required: true },
                    },
                    {
                        id: 69,
                        type: 'date',
                        label: 'Maturity date',
                        condition: { field: 59, op: 'in', value: ['tbill', 'repo', 'corp-bond'] },
                    },
                    {
                        id: 70,
                        type: 'string',
                        label: 'Credit rating',
                        condition: {
                            field: 59,
                            op: 'in',
                            value: ['tbill', 'repo', 'corp-bond', 'mmf'],
                        },
                    },
                    {
                        id: 71,
                        type: 'string',
                        label: 'Counterparty name and trade reference',
                        condition: { field: 59, op: 'eq', value: 'repo' },
                        validation: { required: true },
                    },
                    {
                        id: 72,
                        type: 'string',
                        label: 'Warehouse receipt or vault certificate number',
                        condition: { field: 59, op: 'eq', value: 'commodity' },
                        validation: { required: true },
                    },
                    {
                        id: 73,
                        type: 'string',
                        label: 'Storage or vault location',
                        condition: { field: 59, op: 'eq', value: 'commodity' },
                        validation: { required: true },
                    },
                    {
                        id: 74,
                        type: 'date',
                        label: 'Date of last physical inspection',
                        condition: { field: 59, op: 'eq', value: 'commodity' },
                    },
                    {
                        id: 75,
                        type: 'string',
                        label: 'Title deed reference or property registry ID',
                        condition: { field: 59, op: 'eq', value: 'real-estate' },
                        validation: { required: true },
                    },
                    {
                        id: 76,
                        type: 'string',
                        label: 'Issuer-defined internal reference',
                        condition: { field: 59, op: 'eq', value: 'other' },
                        validation: { required: true },
                    },
                    {
                        id: 77,
                        type: 'string',
                        label: 'Backing asset name',
                        validation: { required: true },
                    },
                    {
                        id: 78,
                        type: 'number',
                        label: 'Nominal or face value',
                        validation: { required: true, min: 0 },
                    },
                    {
                        id: 79,
                        type: 'number',
                        label: 'Market value as of last valuation',
                        validation: { required: true, min: 0 },
                    },
                    {
                        id: 80,
                        type: 'select',
                        label: 'Value update frequency',
                        options: [
                            { value: 'realtime', label: 'Real-time (on-chain feeds)' },
                            { value: 'daily', label: 'Daily NAV' },
                            { value: 'weekly', label: 'Weekly attestation' },
                            { value: 'monthly', label: 'Monthly attestation' },
                            { value: 'quarterly', label: 'Quarterly audit only' },
                        ],
                        validation: { required: true },
                    },
                    {
                        id: 81,
                        type: 'string',
                        label: 'Custodian or holder for this reserve asset',
                        validation: { required: true },
                    },
                    {
                        id: 82,
                        type: 'number',
                        label: 'Percentage of total reserves this asset represents',
                        validation: { required: true, min: 0, max: 100 },
                    },
                    {
                        id: 83,
                        type: 'number',
                        label: 'Current backing-to-supply ratio',
                        validation: { required: true, min: 0 },
                    },
                    {
                        id: 84,
                        type: 'number',
                        label: 'Target backing-to-supply ratio',
                        validation: { required: true, min: 0 },
                    },
                    {
                        id: 85,
                        type: 'string',
                        label: 'Methodology: how are reserves defined?',
                        validation: { required: true },
                    },
                    {
                        id: 86,
                        type: 'boolean',
                        label: 'Are reserve assets rehypothecated, lent, pledged, or otherwise encumbered?',
                        validation: { required: true },
                    },
                    {
                        id: 87,
                        type: 'string',
                        label: 'Explain the encumbrance details',
                        condition: { field: 86, op: 'eq', value: true },
                        validation: { required: true },
                    },
                    {
                        id: 88,
                        type: 'boolean',
                        label: 'Do you agree to notify within 5 business days of any material change to reserve composition?',
                        validation: { required: true },
                    },
                    {
                        id: 89,
                        type: 'string',
                        label: 'Who performs independent reserve verification?',
                        validation: { required: true },
                    },
                    {
                        id: 90,
                        type: 'select',
                        label: 'Verification frequency',
                        options: [
                            { value: 'monthly', label: 'Monthly' },
                            { value: 'quarterly', label: 'Quarterly' },
                            { value: 'semi-annual', label: 'Semi-annually' },
                            { value: 'annual', label: 'Annually' },
                        ],
                        validation: { required: true },
                    },
                    {
                        id: 91,
                        type: 'date',
                        label: 'Date of last independent verification',
                        validation: { required: true },
                    },
                ],
            },
            {
                id: 92,
                type: 'section',
                title: 'Product Category Assessment',
                description: 'Additional questions based on product classification',
                condition: { field: 30, op: 'eq', value: true },
                content: [
                    {
                        id: 93,
                        type: 'section',
                        title: 'Investment Vehicle Details',
                        condition: { field: 31, op: 'eq', value: 'fund' },
                        content: [
                            {
                                id: 94,
                                type: 'string',
                                label: 'Legal name of the issuing fund',
                                validation: { required: true },
                            },
                            {
                                id: 95,
                                type: 'string',
                                label: 'Fund domicile jurisdiction',
                                validation: { required: true },
                            },
                            {
                                id: 96,
                                type: 'select',
                                label: 'Regulatory standing',
                                options: [
                                    { value: 'registered', label: 'Registered' },
                                    { value: 'exempt', label: 'Exempt' },
                                    { value: 'professional', label: 'Professional' },
                                ],
                                validation: { required: true },
                            },
                            {
                                id: 97,
                                type: 'string',
                                label: 'Basis for exemption',
                                condition: { field: 96, op: 'eq', value: 'exempt' },
                                validation: { required: true },
                            },
                            {
                                id: 98,
                                type: 'string',
                                label: 'Investment mandate summary',
                                validation: { required: true },
                            },
                            {
                                id: 99,
                                type: 'string',
                                label: 'NAV calculation frequency',
                                validation: { required: true },
                            },
                            {
                                id: 100,
                                type: 'string',
                                label: 'Redemption frequency',
                                validation: { required: true },
                            },
                            {
                                id: 101,
                                type: 'boolean',
                                label: 'Are there redemption gates or lock-up periods?',
                                validation: { required: true },
                            },
                            {
                                id: 102,
                                type: 'boolean',
                                label: 'Are there investor eligibility restrictions?',
                                validation: { required: true },
                            },
                            {
                                id: 103,
                                type: 'boolean',
                                label: 'Is an independent custodian appointed?',
                                validation: { required: true },
                            },
                            {
                                id: 104,
                                type: 'boolean',
                                label: 'Is a transfer agent appointed?',
                                validation: { required: true },
                            },
                        ],
                    },
                    {
                        id: 105,
                        type: 'section',
                        title: 'Structured Instrument Details',
                        condition: { field: 31, op: 'eq', value: 'note' },
                        content: [
                            {
                                id: 106,
                                type: 'string',
                                label: 'Legal name of the note issuer',
                                validation: { required: true },
                            },
                            {
                                id: 107,
                                type: 'string',
                                label: 'Issuer domicile',
                                validation: { required: true },
                            },
                            {
                                id: 108,
                                type: 'boolean',
                                label: 'Is the issuer a special purpose vehicle?',
                                validation: { required: true },
                            },
                            {
                                id: 109,
                                type: 'string',
                                label: 'Describe the note payoff structure in plain language',
                                validation: { required: true },
                            },
                            {
                                id: 110,
                                type: 'string',
                                label: 'Reference asset or strategy',
                                validation: { required: true },
                            },
                            {
                                id: 111,
                                type: 'boolean',
                                label: 'Is the note secured?',
                                validation: { required: true },
                            },
                            {
                                id: 112,
                                type: 'string',
                                label: 'Noteholder ranking in the issuer capital stack',
                                validation: { required: true },
                            },
                            {
                                id: 113,
                                type: 'boolean',
                                label: 'Are there early redemption or termination rights?',
                                validation: { required: true },
                            },
                            {
                                id: 114,
                                type: 'boolean',
                                label: 'Are there investor eligibility restrictions?',
                                validation: { required: true },
                            },
                        ],
                    },
                    {
                        id: 115,
                        type: 'section',
                        title: 'Credit Pool Details',
                        condition: { field: 31, op: 'eq', value: 'receivables' },
                        content: [
                            {
                                id: 116,
                                type: 'select',
                                label: 'Receivable type',
                                options: [
                                    { value: 'credit-card', label: 'Credit card' },
                                    { value: 'invoice', label: 'Invoice' },
                                    { value: 'trade-finance', label: 'Trade finance' },
                                    { value: 'other', label: 'Other' },
                                ],
                                validation: { required: true },
                            },
                            {
                                id: 117,
                                type: 'string',
                                label: 'Originator identity',
                                validation: { required: true },
                            },
                            {
                                id: 118,
                                type: 'string',
                                label: 'Average receivable tenor',
                                validation: { required: true },
                            },
                            {
                                id: 119,
                                type: 'number',
                                label: 'Maximum obligor concentration (%)',
                                validation: { required: true, min: 0, max: 100 },
                            },
                            {
                                id: 120,
                                type: 'string',
                                label: 'Servicer identity',
                                validation: { required: true },
                            },
                            {
                                id: 121,
                                type: 'boolean',
                                label: 'Is a backup servicer appointed?',
                                validation: { required: true },
                            },
                            {
                                id: 122,
                                type: 'boolean',
                                label: 'Has a true sale been achieved?',
                                validation: { required: true },
                            },
                            {
                                id: 123,
                                type: 'boolean',
                                label: 'Is the security interest perfected?',
                                validation: { required: true },
                            },
                            {
                                id: 124,
                                type: 'number',
                                label: 'Historical default rate (%)',
                                validation: { required: true, min: 0, max: 100 },
                            },
                        ],
                    },
                    {
                        id: 125,
                        type: 'section',
                        title: 'Resource Rights Vehicle Details',
                        condition: { field: 31, op: 'eq', value: 'resource' },
                        content: [
                            {
                                id: 126,
                                type: 'string',
                                label: 'Legal name of the SPV issuer',
                                validation: { required: true },
                            },
                            {
                                id: 127,
                                type: 'string',
                                label: 'SPV domicile jurisdiction',
                                validation: { required: true },
                            },
                            {
                                id: 128,
                                type: 'select',
                                label: 'Asset type',
                                options: [
                                    { value: 'mineral', label: 'Mineral rights' },
                                    { value: 'royalties', label: 'Royalties' },
                                    { value: 'leases', label: 'Leases' },
                                ],
                                validation: { required: true },
                            },
                            {
                                id: 129,
                                type: 'string',
                                label: 'Asset jurisdiction(s)',
                                validation: { required: true },
                            },
                            {
                                id: 130,
                                type: 'string',
                                label: 'Operator identity',
                                validation: { required: true },
                            },
                            {
                                id: 131,
                                type: 'string',
                                label: 'Cash flow source description',
                                validation: { required: true },
                            },
                            {
                                id: 132,
                                type: 'boolean',
                                label: 'Is a third-party reserve or production report available?',
                                validation: { required: true },
                            },
                            {
                                id: 133,
                                type: 'boolean',
                                label: 'Is commodity price hedging used?',
                                validation: { required: true },
                            },
                        ],
                    },
                    {
                        id: 134,
                        type: 'section',
                        title: 'Protected Lending Structure Details',
                        condition: { field: 31, op: 'eq', value: 'spc' },
                        content: [
                            {
                                id: 135,
                                type: 'string',
                                label: 'SPC issuer legal name',
                                validation: { required: true },
                            },
                            {
                                id: 136,
                                type: 'string',
                                label: 'SPC jurisdiction',
                                validation: { required: true },
                            },
                            {
                                id: 137,
                                type: 'boolean',
                                label: 'Is a segregated portfolio used?',
                                validation: { required: true },
                            },
                            {
                                id: 138,
                                type: 'string',
                                label: 'Description of segregation mechanism',
                                validation: { required: true },
                            },
                            {
                                id: 139,
                                type: 'string',
                                label: 'Borrower entity identity',
                                validation: { required: true },
                            },
                            {
                                id: 140,
                                type: 'string',
                                label: 'Underlying collateral type',
                                validation: { required: true },
                            },
                            {
                                id: 141,
                                type: 'boolean',
                                label: 'Are assets commingled across portfolios?',
                                validation: { required: true },
                            },
                            {
                                id: 142,
                                type: 'string',
                                label: 'Liquidity terms including notice period and gates',
                                validation: { required: true },
                            },
                        ],
                    },
                ],
            },
            {
                id: 143,
                type: 'section',
                title: 'Reserve Provider Registry',
                condition: { field: 4, op: 'eq', value: true },
                content: [
                    {
                        id: 144,
                        type: 'array',
                        label: 'Collateral provider names',
                        item: { type: 'string', label: 'Provider name' },
                        validation: { minItems: 1, maxItems: 20 },
                    },
                ],
            },
            {
                id: 145,
                type: 'section',
                title: 'Attestations & Agreements',
                content: [
                    {
                        id: 146,
                        type: 'boolean',
                        label: 'I acknowledge that submitted information may be publicly visible',
                        validation: { required: true },
                    },
                    {
                        id: 147,
                        type: 'boolean',
                        label: 'I accept responsibility for ongoing regulatory compliance',
                        validation: { required: true },
                    },
                    {
                        id: 148,
                        type: 'boolean',
                        label: 'I accept the terms of service and privacy policy',
                        validation: { required: true },
                    },
                ],
            },
        ],
    },
    values: {
        '2': true,
        '3': true,
        '4': true,
        '6': 'Horizon Yield Token',
        '7': 'A digital representation of diversified fixed-income portfolio interests, providing fractional access to institutional-grade instruments.',
        '8': 'Meridian Capital Holdings Ltd.',
        '9': 'spc',
        '10': 'Cayman Islands',
        '11': 'Meridian Capital Holdings operates as a structured finance vehicle focused on tokenized fixed-income products.',
        '12': 'https://meridian-capital.example.com',
        '16': '0x742d35Cc6634C0532925a3b844Bc9e7595f2bD18',
        '17': 'Horizon Yield Token',
        '18': 'HYT',
        '19': 'all-rights',
        '20': 'https://docs.meridian-capital.example.com/hyt-whitepaper',
        '21': 'https://meridian-capital.example.com',
        '22': 'Ethereum',
        '23': 'ERC-20',
        '24': 'owner',
        '30': true,
        '31': 'fund',
        '32': 'ky',
        '33': true,
        '34': 'Limited to accredited investors and qualified purchasers under applicable securities regulations.',
        '38': true,
        '39': 'Meridian SPC operates as a segregated portfolio company with each fund isolated as a separate portfolio.',
        '40': 'Assets are held under a first-priority perfected security interest in favor of token holders.',
        '45': true,
        '46': 'Apex Fund Services (Cayman) Ltd.',
        '47': 'All fund assets are held in segregated accounts with daily reconciliation.',
        '48': false,
        '54': 'audited',
        '56': 'KPMG Cayman Islands',
        '57': '2025-09-30T00:00:00.000Z',
        '59': 'tbill',
        '68': 'US912797HZ58',
        '69': '2026-06-15T00:00:00.000Z',
        '70': 'AAA',
        '77': 'US Treasury Bill 6-Month',
        '78': 10000000,
        '79': 9950000,
        '80': 'daily',
        '81': 'Apex Fund Services (Cayman) Ltd.',
        '82': 65,
        '83': 1.05,
        '84': 1.1,
        '85': 'Reserves include all assets held in segregated custody accounts plus accrued interest, measured at fair market value.',
        '86': false,
        '88': true,
        '89': 'KPMG Cayman Islands',
        '90': 'quarterly',
        '91': '2025-09-30T00:00:00.000Z',
        '94': 'Meridian Horizon Fund SPC',
        '95': 'Cayman Islands',
        '96': 'exempt',
        '97': 'Section 4(3) of the Mutual Funds Act — registered as a restricted scope fund.',
        '98': 'Invest primarily in short-duration US Treasury securities and investment-grade fixed income instruments.',
        '99': 'Daily',
        '100': 'Monthly with 30-day notice',
        '101': true,
        '102': true,
        '103': true,
        '104': true,
        '144': ['Apex Fund Services', 'US Treasury Direct'],
        '146': true,
        '147': true,
        '148': true,
    },
}
