import type { SampleForm } from './types'

export const CUSTODY_ASSESSMENT: SampleForm = {
    label: 'Custody Assessment (3 levels)',
    submittedAt: '2025-11-05T09:15:00.000Z',
    definition: {
        id: '2cf77b35-b1c0-45ae-8cac-6694e49b99d8',
        version: '1.0.0',
        title: 'Digital Asset Custody Assessment',
        description: 'Evaluate custodial controls and safekeeping practices for digital assets',
        content: [
            {
                id: 1,
                type: 'string',
                label: 'Assessment reference number',
                validation: { required: true },
            },
            {
                id: 2,
                type: 'section',
                title: 'Custodian Profile',
                description: 'General information about the custodial entity',
                content: [
                    {
                        id: 3,
                        type: 'string',
                        label: 'Custodian legal name',
                        validation: { required: true },
                    },
                    {
                        id: 4,
                        type: 'number',
                        label: 'Assets under custody (USD)',
                        validation: { required: true, min: 0 },
                    },
                    {
                        id: 5,
                        type: 'section',
                        title: 'Operational Controls',
                        description: 'Key personnel and operational procedures',
                        content: [
                            {
                                id: 6,
                                type: 'string',
                                label: 'Chief Security Officer name',
                                validation: { required: true },
                            },
                            {
                                id: 7,
                                type: 'string',
                                label: 'CSO contact email',
                                validation: { required: true },
                            },
                            {
                                id: 8,
                                type: 'section',
                                title: 'Key Management',
                                description: 'Private key storage and signing procedures',
                                content: [
                                    {
                                        id: 9,
                                        type: 'select',
                                        label: 'Primary key storage method',
                                        options: [
                                            { value: 'hsm', label: 'Hardware Security Module' },
                                            { value: 'mpc', label: 'Multi-Party Computation' },
                                            { value: 'multisig', label: 'Multi-signature' },
                                            { value: 'hybrid', label: 'Hybrid' },
                                            { value: 'other', label: 'Other' },
                                        ],
                                        validation: { required: true },
                                    },
                                    {
                                        id: 10,
                                        type: 'number',
                                        label: 'Required signers for withdrawal',
                                        validation: { required: true, min: 1, max: 10 },
                                    },
                                    {
                                        id: 11,
                                        type: 'boolean',
                                        label: 'Air-gapped signing environment?',
                                    },
                                    {
                                        id: 12,
                                        type: 'array',
                                        label: 'Supported key curves',
                                        item: { type: 'string', label: 'Curve' },
                                        validation: { maxItems: 10 },
                                    },
                                ],
                            },
                        ],
                    },
                ],
            },
            {
                id: 13,
                type: 'section',
                title: 'Security Infrastructure',
                description: 'Insurance, cold storage, and disaster recovery',
                content: [
                    {
                        id: 14,
                        type: 'select',
                        label: 'Insurance coverage type',
                        options: [
                            { value: 'full', label: 'Full coverage' },
                            { value: 'partial', label: 'Partial coverage' },
                            { value: 'none', label: 'No coverage' },
                        ],
                        validation: { required: true },
                    },
                    {
                        id: 15,
                        type: 'number',
                        label: 'Insurance coverage amount (USD)',
                        condition: { field: 14, op: 'in', value: ['full', 'partial'] },
                        validation: { required: true, min: 0 },
                    },
                    {
                        id: 16,
                        type: 'section',
                        title: 'Cold Storage',
                        description: 'Offline asset storage arrangements',
                        content: [
                            {
                                id: 17,
                                type: 'boolean',
                                label: 'Cold storage utilized?',
                                validation: { required: true },
                            },
                            {
                                id: 18,
                                type: 'number',
                                label: 'Cold storage percentage (%)',
                                condition: { field: 17, op: 'eq', value: true },
                                validation: { required: true, min: 0, max: 100 },
                            },
                            {
                                id: 19,
                                type: 'string',
                                label: 'Cold storage facility location',
                                condition: { field: 17, op: 'eq', value: true },
                                validation: { required: true },
                            },
                            {
                                id: 20,
                                type: 'section',
                                title: 'Disaster Recovery',
                                description: 'Recovery and redundancy provisions',
                                content: [
                                    {
                                        id: 21,
                                        type: 'boolean',
                                        label: 'Geographic redundancy?',
                                        validation: { required: true },
                                    },
                                    {
                                        id: 22,
                                        type: 'number',
                                        label: 'Number of backup locations',
                                        condition: { field: 21, op: 'eq', value: true },
                                        validation: { min: 1 },
                                    },
                                    {
                                        id: 23,
                                        type: 'select',
                                        label: 'Recovery time objective',
                                        options: [
                                            { value: '1h', label: 'Under 1 hour' },
                                            { value: '4h', label: '1–4 hours' },
                                            { value: '24h', label: '4–24 hours' },
                                            { value: '72h', label: '24–72 hours' },
                                        ],
                                        validation: { required: true },
                                    },
                                    {
                                        id: 24,
                                        type: 'date',
                                        label: 'Last DR drill date',
                                    },
                                ],
                            },
                        ],
                    },
                ],
            },
            {
                id: 25,
                type: 'section',
                title: 'Compliance & Audit',
                description: 'Certification, proof of reserves, and third-party audits',
                content: [
                    {
                        id: 26,
                        type: 'boolean',
                        label: 'SOC 2 Type II certified?',
                        validation: { required: true },
                    },
                    {
                        id: 27,
                        type: 'date',
                        label: 'SOC 2 report date',
                        condition: { field: 26, op: 'eq', value: true },
                    },
                    {
                        id: 28,
                        type: 'select',
                        label: 'Proof of reserves frequency',
                        options: [
                            { value: 'real-time', label: 'Real-time' },
                            { value: 'daily', label: 'Daily' },
                            { value: 'monthly', label: 'Monthly' },
                            { value: 'quarterly', label: 'Quarterly' },
                        ],
                        validation: { required: true },
                    },
                    {
                        id: 29,
                        type: 'boolean',
                        label: 'Third-party audit completed?',
                        validation: { required: true },
                    },
                    {
                        id: 30,
                        type: 'string',
                        label: 'Auditor name',
                        condition: { field: 29, op: 'eq', value: true },
                        validation: { required: true },
                    },
                    {
                        id: 31,
                        type: 'date',
                        label: 'Last audit date',
                        condition: { field: 29, op: 'eq', value: true },
                    },
                ],
            },
            {
                id: 32,
                type: 'boolean',
                label: 'I confirm this assessment is accurate and complete',
                validation: { required: true },
            },
        ],
    },
    values: {
        '1': 'CA-2025-0047',
        '3': 'Fireblocks Ltd.',
        '4': 4200000000,
        '6': 'Michael Torres',
        '7': 'm.torres@fireblocks.example.com',
        '9': 'mpc',
        '10': 3,
        '11': true,
        '12': ['secp256k1', 'ed25519', 'BLS12-381'],
        '14': 'full',
        '15': 500000000,
        '17': true,
        '18': 95,
        '19': 'Zurich, Switzerland (primary); Singapore (secondary)',
        '21': true,
        '22': 3,
        '23': '1h',
        '24': '2025-09-15T00:00:00.000Z',
        '26': true,
        '27': '2025-06-30T00:00:00.000Z',
        '28': 'real-time',
        '29': true,
        '30': 'Deloitte',
        '31': '2025-08-01T00:00:00.000Z',
        '32': true,
    },
}
