import type { SampleForm } from './types'

export const PORTFOLIO_DECLARATION: SampleForm = {
    label: 'Portfolio Declaration (Array Variants)',
    submittedAt: '2025-12-31T23:59:00.000Z',
    definition: {
        id: 'e4a7c1b2-3d5f-4890-abef-1234567890ab',
        version: '1.0.0',
        title: 'Digital Asset Portfolio Declaration',
        description:
            'Declare digital asset holdings with per-position data and evidence for regulatory compliance. Demonstrates all array item types.',
        content: [
            {
                id: 1,
                type: 'section',
                title: 'Declarant Information',
                content: [
                    {
                        id: 2,
                        type: 'string',
                        label: 'Declaring entity name',
                        validation: { required: true },
                    },
                    {
                        id: 3,
                        type: 'string',
                        label: 'Declaration reference number',
                        validation: { required: true },
                    },
                    {
                        id: 4,
                        type: 'date',
                        label: 'Declaration effective date',
                        validation: { required: true },
                    },
                    {
                        id: 5,
                        type: 'select',
                        label: 'Declaration type',
                        options: [
                            { value: 'initial', label: 'Initial Declaration' },
                            { value: 'periodic', label: 'Periodic Update' },
                            { value: 'event-driven', label: 'Event-Driven Update' },
                        ],
                        validation: { required: true },
                    },
                    {
                        id: 6,
                        type: 'string',
                        label: 'Triggering event description',
                        condition: { field: 5, op: 'eq', value: 'event-driven' },
                        validation: { required: true, minLength: 10 },
                    },
                ],
            },
            {
                id: 7,
                type: 'section',
                title: 'Wallet Registry',
                description: 'Array of string — all wallet addresses under entity control',
                content: [
                    {
                        id: 8,
                        type: 'array',
                        label: 'Controlled wallet addresses',
                        item: {
                            type: 'string',
                            label: 'Wallet address',
                            validation: { required: true },
                        },
                        validation: { minItems: 1, maxItems: 100 },
                    },
                    {
                        id: 9,
                        type: 'select',
                        label: 'Primary blockchain network',
                        options: [
                            { value: 'ethereum', label: 'Ethereum' },
                            { value: 'bitcoin', label: 'Bitcoin' },
                            { value: 'solana', label: 'Solana' },
                            { value: 'polygon', label: 'Polygon' },
                            { value: 'multi', label: 'Multi-chain' },
                        ],
                        validation: { required: true },
                    },
                    {
                        id: 10,
                        type: 'array',
                        label: 'Additional chain identifiers',
                        item: { type: 'string', label: 'Chain name or ID' },
                        condition: { field: 9, op: 'eq', value: 'multi' },
                        validation: { minItems: 2, maxItems: 20 },
                    },
                ],
            },
            {
                id: 11,
                type: 'section',
                title: 'Position Valuations',
                description: 'Array of number — USD value for each declared position',
                content: [
                    {
                        id: 12,
                        type: 'array',
                        label: 'Individual position values (USD)',
                        item: {
                            type: 'number',
                            label: 'Position value (USD)',
                            validation: { required: true, min: 0 },
                        },
                        validation: { minItems: 1, maxItems: 100 },
                    },
                    {
                        id: 13,
                        type: 'number',
                        label: 'Total declared portfolio value (USD)',
                        validation: { required: true, min: 0 },
                    },
                ],
            },
            {
                id: 14,
                type: 'section',
                title: 'Risk Classifications',
                description: 'Array of select — risk category assigned to each position',
                content: [
                    {
                        id: 15,
                        type: 'array',
                        label: 'Position risk classifications',
                        item: {
                            type: 'select',
                            label: 'Risk classification',
                            options: [
                                { value: 'low', label: 'Low Risk' },
                                { value: 'medium', label: 'Medium Risk' },
                                { value: 'high', label: 'High Risk' },
                                { value: 'prohibited', label: 'Prohibited' },
                            ],
                        },
                        validation: { minItems: 1, maxItems: 100 },
                    },
                ],
            },
            {
                id: 16,
                type: 'section',
                title: 'Compliance Review Dates',
                description: 'Array of date — last compliance review date per position',
                content: [
                    {
                        id: 17,
                        type: 'array',
                        label: 'Last compliance review dates',
                        item: { type: 'date', label: 'Review date' },
                        validation: { maxItems: 100 },
                    },
                    {
                        id: 18,
                        type: 'date',
                        label: 'Next scheduled portfolio-wide review',
                    },
                ],
            },
            {
                id: 19,
                type: 'section',
                title: 'Sanctions Screening',
                description: 'Array of boolean — pass/fail screening result per position',
                content: [
                    {
                        id: 20,
                        type: 'array',
                        label: 'Sanctions screening results (pass = true)',
                        item: { type: 'boolean', label: 'Passed sanctions screening' },
                        validation: { minItems: 1, maxItems: 100 },
                    },
                    {
                        id: 21,
                        type: 'boolean',
                        label: 'All positions passed sanctions screening?',
                        validation: { required: true },
                    },
                    {
                        id: 22,
                        type: 'string',
                        label: 'Explain screening failures and remediation steps',
                        condition: { field: 21, op: 'eq', value: false },
                        validation: { required: true, minLength: 20 },
                    },
                ],
            },
            {
                id: 23,
                type: 'section',
                title: 'Evidence Package',
                description: 'Array of file — supporting documents for each position',
                content: [
                    {
                        id: 24,
                        type: 'array',
                        label: 'Position-level evidence documents',
                        item: { type: 'file', label: 'Evidence document' },
                        validation: { minItems: 1, maxItems: 50 },
                    },
                    {
                        id: 25,
                        type: 'file',
                        label: 'Consolidated portfolio report',
                    },
                    {
                        id: 26,
                        type: 'string',
                        label: 'Compliance officer notes',
                        validation: { maxLength: 5000 },
                    },
                ],
            },
            {
                id: 27,
                type: 'section',
                title: 'Attestation',
                content: [
                    {
                        id: 28,
                        type: 'string',
                        label: 'Compliance officer name',
                        validation: { required: true },
                    },
                    {
                        id: 29,
                        type: 'date',
                        label: 'Attestation date',
                        validation: { required: true },
                    },
                    {
                        id: 30,
                        type: 'boolean',
                        label: 'I confirm all declared positions and valuations are accurate and complete',
                        validation: { required: true },
                    },
                    {
                        id: 31,
                        type: 'boolean',
                        label: 'I confirm all required sanctions screening has been completed',
                        validation: { required: true },
                    },
                ],
            },
        ],
    },
    values: {
        '2': 'Apex Digital Exchange Pte. Ltd.',
        '3': 'PD-2025-Q4-0012',
        '4': '2025-12-31T00:00:00.000Z',
        '5': 'periodic',
        '8': [
            '0x742d35Cc6634C0532925a3b844Bc9e7595f2bD18',
            '0xDEAD000000000000000000000000000000000001',
            'bc1qar0srrr7xfkvy5l643lydnw9re59gtzzwf5mdq',
            '0xABCDEF1234567890ABCDEF1234567890ABCDEF12',
        ],
        '9': 'multi',
        '10': ['Ethereum', 'Bitcoin', 'Polygon'],
        '12': [1250000, 890000, 425000, 75000],
        '13': 2640000,
        '15': ['low', 'low', 'medium', 'high'],
        '17': [
            '2025-12-15T00:00:00.000Z',
            '2025-12-15T00:00:00.000Z',
            '2025-12-01T00:00:00.000Z',
            '2025-11-20T00:00:00.000Z',
        ],
        '18': '2026-03-31T00:00:00.000Z',
        '20': [true, true, true, false],
        '21': false,
        '22': 'Position 4 flagged for indirect exposure to sanctioned mixer contract. Funds frozen pending investigation; SAR filed 2025-11-22.',
        '24': [
            {
                name: 'position-1-evidence.pdf',
                mimeType: 'application/pdf',
                size: 245760,
                url: 'https://storage.example.com/compliance/portfolio/position-1-evidence.pdf',
            },
            {
                name: 'position-2-evidence.pdf',
                mimeType: 'application/pdf',
                size: 198400,
                url: 'https://storage.example.com/compliance/portfolio/position-2-evidence.pdf',
            },
            {
                name: 'position-3-chainalysis.pdf',
                mimeType: 'application/pdf',
                size: 153600,
                url: 'https://storage.example.com/compliance/portfolio/position-3-chainalysis.pdf',
            },
            {
                name: 'position-4-investigation.pdf',
                mimeType: 'application/pdf',
                size: 512000,
                url: 'https://storage.example.com/compliance/portfolio/position-4-investigation.pdf',
            },
        ],
        '25': {
            name: 'q4-2025-portfolio-report.pdf',
            mimeType: 'application/pdf',
            size: 1048576,
            url: 'https://storage.example.com/compliance/portfolio/q4-2025-portfolio-report.pdf',
        },
        '26': 'Q4 periodic declaration. Position 4 under active investigation — see SAR PD-SAR-2025-0047.',
        '28': 'Rachel Tan',
        '29': '2025-12-31T00:00:00.000Z',
        '30': true,
        '31': true,
    },
}
