import type { SampleForm } from './types'

export const SUSPICIOUS_ACTIVITY_REPORT: SampleForm = {
    label: 'Suspicious Activity Report',
    submittedAt: '2025-11-22T08:30:00.000Z',
    definition: {
        id: 'de86a89e-9ab0-43f7-96ab-ca6b2ece3855',
        version: '1.0.0',
        title: 'Suspicious Activity Report',
        description: 'File a report for suspicious cryptocurrency transaction activity',
        content: [
            {
                id: 1,
                type: 'date',
                label: 'Date of suspicious activity',
                validation: { required: true },
            },
            {
                id: 2,
                type: 'select',
                label: 'Activity type',
                options: [
                    { value: 'large-transfer', label: 'Unusually large transfer' },
                    { value: 'structuring', label: 'Transaction structuring' },
                    { value: 'mixing', label: 'Use of mixing / tumbling service' },
                    { value: 'darknet', label: 'Darknet marketplace interaction' },
                    { value: 'fraud', label: 'Suspected fraud' },
                    { value: 'sanctions', label: 'Potential sanctions violation' },
                    { value: 'other', label: 'Other' },
                ],
                validation: { required: true },
            },
            {
                id: 3,
                type: 'string',
                label: 'Specify activity type',
                condition: { field: 2, op: 'eq', value: 'other' },
                validation: { required: true },
            },
            {
                id: 4,
                type: 'string',
                label: 'Wallet address(es) involved',
                validation: { required: true },
            },
            {
                id: 5,
                type: 'select',
                label: 'Blockchain network',
                options: [
                    { value: 'bitcoin', label: 'Bitcoin' },
                    { value: 'ethereum', label: 'Ethereum' },
                    { value: 'tron', label: 'TRON' },
                    { value: 'solana', label: 'Solana' },
                    { value: 'polygon', label: 'Polygon' },
                    { value: 'bnb', label: 'BNB Chain' },
                    { value: 'other', label: 'Other' },
                ],
                validation: { required: true },
            },
            {
                id: 6,
                type: 'number',
                label: 'Estimated value (USD)',
                validation: { required: true, min: 0 },
            },
            {
                id: 7,
                type: 'string',
                label: 'Description of suspicious activity',
                validation: { required: true, minLength: 50, maxLength: 5000 },
            },
            {
                id: 8,
                type: 'boolean',
                label: 'Has this been reported to law enforcement?',
                validation: { required: true },
            },
            {
                id: 9,
                type: 'string',
                label: 'Law enforcement reference number',
                condition: { field: 8, op: 'eq', value: true },
            },
            {
                id: 10,
                type: 'string',
                label: 'Reporting officer name',
                validation: { required: true },
            },
            {
                id: 11,
                type: 'string',
                label: 'Reporting officer email',
                validation: {
                    required: true,
                    pattern: '^[^@]+@[^@]+\\.[^@]+$',
                    patternMessage: 'Must be a valid email address',
                },
            },
            {
                id: 12,
                type: 'boolean',
                label: 'I confirm this report is filed in good faith',
                validation: { required: true },
            },
        ],
    },
    values: {
        '1': '2025-11-20T00:00:00.000Z',
        '2': 'large-transfer',
        '4': '0xDEAD000000000000000000000000000000000001',
        '5': 'ethereum',
        '6': 2400000,
        '7': 'Multiple large transfers totaling $2.4M routed through a newly created wallet within a 3-hour window, with funds immediately bridged to a separate chain.',
        '8': false,
        '10': 'James Wong',
        '11': 'j.wong@exchange.example.com',
        '12': true,
    },
}
