import type { SampleForm } from './types'

export const TRAVEL_RULE_REPORT: SampleForm = {
    label: 'Travel Rule Report',
    definition: {
        id: 'c7e2a4f0-8b1d-4e3a-9f6c-d5a2b8e1c4f7',
        version: '1.0.0',
        title: 'Travel Rule Compliance Report',
        description: 'Submit travel rule transaction data and supporting documentation for regulatory compliance',
        content: [
            {
                id: 1,
                type: 'section',
                title: 'Transaction Details',
                content: [
                    {
                        id: 2,
                        type: 'string',
                        label: 'Transaction hash',
                        validation: { required: true },
                    },
                    {
                        id: 3,
                        type: 'select',
                        label: 'Blockchain network',
                        options: [
                            { value: 'bitcoin', label: 'Bitcoin' },
                            { value: 'ethereum', label: 'Ethereum' },
                            { value: 'polygon', label: 'Polygon' },
                            { value: 'solana', label: 'Solana' },
                            { value: 'tron', label: 'TRON' },
                            { value: 'other', label: 'Other' },
                        ],
                        validation: { required: true },
                    },
                    {
                        id: 4,
                        type: 'date',
                        label: 'Transaction date',
                        validation: { required: true },
                    },
                    {
                        id: 5,
                        type: 'number',
                        label: 'Transaction amount (USD equivalent)',
                        validation: { required: true, min: 0 },
                    },
                    {
                        id: 6,
                        type: 'select',
                        label: 'Transfer direction',
                        options: [
                            { value: 'outgoing', label: 'Outgoing' },
                            { value: 'incoming', label: 'Incoming' },
                        ],
                        validation: { required: true },
                    },
                ],
            },
            {
                id: 7,
                type: 'section',
                title: 'Originator Information',
                content: [
                    {
                        id: 8,
                        type: 'string',
                        label: 'Originator name',
                        validation: { required: true },
                    },
                    {
                        id: 9,
                        type: 'string',
                        label: 'Originator wallet address',
                        validation: { required: true },
                    },
                    {
                        id: 10,
                        type: 'string',
                        label: 'Originator institution (counterparty VASP)',
                        condition: { field: 6, op: 'eq', value: 'incoming' },
                        validation: { required: true },
                    },
                    {
                        id: 11,
                        type: 'file',
                        label: 'Originator identity verification',
                        validation: { required: true },
                    },
                ],
            },
            {
                id: 12,
                type: 'section',
                title: 'Beneficiary Information',
                content: [
                    {
                        id: 13,
                        type: 'string',
                        label: 'Beneficiary name',
                        validation: { required: true },
                    },
                    {
                        id: 14,
                        type: 'string',
                        label: 'Beneficiary wallet address',
                        validation: { required: true },
                    },
                    {
                        id: 15,
                        type: 'string',
                        label: 'Beneficiary institution (counterparty VASP)',
                        condition: { field: 6, op: 'eq', value: 'outgoing' },
                        validation: { required: true },
                    },
                    {
                        id: 16,
                        type: 'file',
                        label: 'Beneficiary identity verification',
                    },
                ],
            },
            {
                id: 17,
                type: 'section',
                title: 'Compliance Documentation',
                content: [
                    {
                        id: 18,
                        type: 'file',
                        label: 'Transaction screening report',
                        validation: { required: true },
                    },
                    {
                        id: 19,
                        type: 'boolean',
                        label: 'Enhanced due diligence required?',
                        validation: { required: true },
                    },
                    {
                        id: 20,
                        type: 'file',
                        label: 'EDD report',
                        condition: { field: 19, op: 'eq', value: true },
                    },
                    {
                        id: 21,
                        type: 'array',
                        label: 'Supporting documents',
                        item: { type: 'file', label: 'Document' },
                        validation: { maxItems: 10 },
                    },
                    {
                        id: 22,
                        type: 'string',
                        label: 'Compliance officer notes',
                        validation: { maxLength: 5000 },
                    },
                ],
            },
            {
                id: 23,
                type: 'section',
                title: 'Attestation',
                content: [
                    {
                        id: 24,
                        type: 'string',
                        label: 'Compliance officer name',
                        validation: { required: true },
                    },
                    {
                        id: 25,
                        type: 'date',
                        label: 'Review date',
                        validation: { required: true },
                    },
                    {
                        id: 26,
                        type: 'boolean',
                        label: 'I confirm travel rule obligations have been met for this transaction',
                        validation: { required: true },
                    },
                    {
                        id: 27,
                        type: 'boolean',
                        label: 'I confirm all originator and beneficiary data is complete and accurate',
                        validation: { required: true },
                    },
                ],
            },
        ],
    },
    values: {
        '2': '0xabc123def456789012345678901234567890abcdef1234567890abcdef123456',
        '3': 'ethereum',
        '4': '2025-12-05T00:00:00.000Z',
        '5': 75000,
        '6': 'outgoing',
        '8': 'Apex Digital Exchange Pte. Ltd. (on behalf of client)',
        '9': '0x742d35Cc6634C0532925a3b844Bc9e7595f2bD18',
        '13': 'Meridian Capital Holdings Ltd.',
        '14': '0xDEAD000000000000000000000000000000000002',
        '15': 'Coinbase Custody International',
        '11': {
            name: 'originator-kyc.pdf',
            mimeType: 'application/pdf',
            size: 245760,
            url: 'https://storage.example.com/compliance/travel-rule/originator-kyc.pdf',
        },
        '16': {
            name: 'beneficiary-kyc.pdf',
            mimeType: 'application/pdf',
            size: 198400,
            url: 'https://storage.example.com/compliance/travel-rule/beneficiary-kyc.pdf',
        },
        '18': {
            name: 'screening-report.pdf',
            mimeType: 'application/pdf',
            size: 153600,
            url: 'https://storage.example.com/compliance/travel-rule/screening-report.pdf',
        },
        '19': false,
        '21': [
            {
                name: 'source-of-funds.pdf',
                mimeType: 'application/pdf',
                size: 307200,
                url: 'https://storage.example.com/compliance/travel-rule/source-of-funds.pdf',
            },
        ],
        '22': 'Standard outgoing transfer to institutional counterparty. All screening passed, no adverse flags.',
        '24': 'Rachel Tan',
        '25': '2025-12-05T00:00:00.000Z',
        '26': true,
        '27': true,
    },
}
