import type { SampleForm } from './types'

export const VASP_REGISTRATION: SampleForm = {
    label: 'VASP Registration',
    submittedAt: '2025-10-08T16:20:00.000Z',
    definition: {
        id: '3396368d-6a02-48c4-a2e9-8ffb458d3f81',
        version: '1.0.0',
        title: 'VASP Registration',
        description: 'Register as a Virtual Asset Service Provider under regulatory requirements',
        content: [
            {
                id: 1,
                type: 'section',
                title: 'Entity Information',
                content: [
                    {
                        id: 2,
                        type: 'string',
                        label: 'Legal entity name',
                        validation: { required: true },
                    },
                    {
                        id: 3,
                        type: 'string',
                        label: 'Registration number',
                        validation: { required: true },
                    },
                    {
                        id: 4,
                        type: 'select',
                        label: 'Entity type',
                        options: [
                            { value: 'exchange', label: 'Exchange' },
                            { value: 'custodian', label: 'Custodian' },
                            { value: 'wallet', label: 'Wallet Provider' },
                            { value: 'defi', label: 'DeFi Protocol' },
                            { value: 'broker', label: 'Broker-Dealer' },
                            { value: 'other', label: 'Other' },
                        ],
                        validation: { required: true },
                    },
                    {
                        id: 5,
                        type: 'string',
                        label: 'Primary jurisdiction',
                        validation: { required: true },
                    },
                    {
                        id: 6,
                        type: 'date',
                        label: 'Date of incorporation',
                        validation: { required: true },
                    },
                    {
                        id: 7,
                        type: 'string',
                        label: 'Principal place of business',
                        validation: { required: true },
                    },
                ],
            },
            {
                id: 8,
                type: 'section',
                title: 'Services & Operations',
                content: [
                    {
                        id: 9,
                        type: 'array',
                        label: 'Virtual asset services offered',
                        item: { type: 'string', label: 'Service' },
                        validation: { minItems: 1, maxItems: 10 },
                    },
                    {
                        id: 10,
                        type: 'number',
                        label: 'Monthly transaction volume (USD)',
                        validation: { required: true, min: 0 },
                    },
                    {
                        id: 11,
                        type: 'number',
                        label: 'Number of active users',
                        validation: { required: true, min: 0 },
                    },
                    {
                        id: 12,
                        type: 'select',
                        label: 'Operational status',
                        options: [
                            { value: 'operational', label: 'Fully operational' },
                            { value: 'pre-launch', label: 'Pre-launch' },
                            { value: 'limited', label: 'Limited operations' },
                        ],
                        validation: { required: true },
                    },
                ],
            },
            {
                id: 13,
                type: 'section',
                title: 'Compliance Infrastructure',
                content: [
                    {
                        id: 14,
                        type: 'boolean',
                        label: 'AML/CFT program established?',
                        validation: { required: true },
                    },
                    {
                        id: 15,
                        type: 'string',
                        label: 'Compliance officer name',
                        condition: { field: 14, op: 'eq', value: true },
                        validation: { required: true },
                    },
                    {
                        id: 16,
                        type: 'boolean',
                        label: 'Travel Rule compliance implemented?',
                        condition: { field: 14, op: 'eq', value: true },
                    },
                    {
                        id: 17,
                        type: 'select',
                        label: 'Travel Rule solution provider',
                        condition: {
                            and: [
                                { field: 14, op: 'eq', value: true },
                                { field: 16, op: 'eq', value: true },
                            ],
                        },
                        options: [
                            { value: 'notabene', label: 'Notabene' },
                            { value: 'chainalysis', label: 'Chainalysis' },
                            { value: 'trisa', label: 'TRISA' },
                            { value: 'sygna', label: 'Sygna Bridge' },
                            { value: 'other', label: 'Other' },
                        ],
                    },
                    {
                        id: 18,
                        type: 'boolean',
                        label: 'Transaction monitoring system in place?',
                        validation: { required: true },
                    },
                    {
                        id: 19,
                        type: 'string',
                        label: 'Transaction monitoring vendor',
                        condition: { field: 18, op: 'eq', value: true },
                    },
                ],
            },
            {
                id: 20,
                type: 'section',
                title: 'Risk Assessment',
                content: [
                    {
                        id: 21,
                        type: 'select',
                        label: 'Overall risk rating',
                        options: [
                            { value: 'low', label: 'Low' },
                            { value: 'medium', label: 'Medium' },
                            { value: 'high', label: 'High' },
                            { value: 'critical', label: 'Critical' },
                        ],
                        validation: { required: true },
                    },
                    {
                        id: 22,
                        type: 'number',
                        label: 'High-risk customers (%)',
                        condition: { field: 21, op: 'in', value: ['high', 'critical'] },
                        validation: { required: true, min: 0, max: 100 },
                    },
                    {
                        id: 23,
                        type: 'array',
                        label: 'Jurisdictions of operation',
                        item: { type: 'string', label: 'Jurisdiction' },
                        validation: { minItems: 1, maxItems: 50 },
                    },
                    {
                        id: 24,
                        type: 'boolean',
                        label: 'Operates in FATF grey-list jurisdictions?',
                        validation: { required: true },
                    },
                    {
                        id: 25,
                        type: 'string',
                        label: 'Grey-list jurisdiction details and mitigation measures',
                        condition: { field: 24, op: 'eq', value: true },
                        validation: { required: true },
                    },
                ],
            },
            {
                id: 26,
                type: 'boolean',
                label: 'I confirm the entity meets all applicable regulatory requirements',
                validation: { required: true },
            },
            {
                id: 27,
                type: 'boolean',
                label: 'I authorize the regulatory authority to verify submitted information',
                validation: { required: true },
            },
        ],
    },
    values: {
        '2': 'Apex Digital Exchange Pte. Ltd.',
        '3': '202301234K',
        '4': 'exchange',
        '5': 'Singapore',
        '6': '2023-01-15T00:00:00.000Z',
        '7': '1 Raffles Place, Tower One, Singapore 048616',
        '9': ['Fiat-to-crypto exchange', 'Crypto-to-crypto exchange', 'Custody services'],
        '10': 85000000,
        '11': 142000,
        '12': 'operational',
        '14': true,
        '15': 'Rachel Tan',
        '16': true,
        '17': 'notabene',
        '18': true,
        '19': 'Chainalysis KYT',
        '21': 'medium',
        '23': ['Singapore', 'Hong Kong', 'Japan', 'Australia', 'European Union'],
        '24': false,
        '26': true,
        '27': true,
    },
}
